#!/bin/bash

HICOLOR="/usr/share/icons/hicolor"

if (( $EUID != 0 )); then
	if [[ -t 1 ]]; then
		sudo "$0" "$@"
	else
		exec 1>output_file
		gksu "$0 $@"
	fi
	exit
fi

if [ -d $HICOLOR/16x16/apps ]; then
	echo "Moving 16x16 photo."
	rm $HICOLOR/16x16/apps/teamspeak3.png
fi

if [ -d $HICOLOR/22x22/apps ]; then
	echo "Moving 22x22 photo."
	rm $HICOLOR/22x22/apps/teamspeak3.png
fi

if [ -d $HICOLOR/16x16/apps ]; then
	echo "Moving 24x24 photo."
	rm $HICOLOR/24x24/apps/teamspeak3.png
fi

if [ -d $HICOLOR/32x32/apps ]; then
	echo "Moving 32x32 photo."
	rm $HICOLOR/32x32/apps/teamspeak3.png
fi

if [ -d $HICOLOR/48x48/apps ]; then
	echo "Moving 48x48 photo."
	rm $HICOLOR/48x48/apps/teamspeak3.png
fi

if [ -d $HICOLOR/64x64/apps ]; then
	echo "Moving 64x64 photo."
	rm $HICOLOR/64x64/apps/teamspeak3.png
fi

rm /usr/share/applications/teamspeak3.desktop

gtk-update-icon-cache -f /usr/share/icons/hicolor/
